apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  # modify replicas according to your case
  replicas: 4
  selector:
    matchLabels:
      app: tesla
  template:
    metadata:
      name: javaapp
      labels:
        app: tesla
    spec:
      containers:
      - name: java-web-app
        image: obinnaaliogor/java-web-app
        ports:
        - containerPort:  8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaappsvc
spec:
  selector:
    app: tesla
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8080
