kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adminrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-access_binding
subjects:
- kind: User
  name: dominion                           # Map with username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: adminrole
  apiGroup: rbac.authorization.k8s.io