apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongoapp
  labels:
    app: mongoapp
spec:
  # modify replicas according to your case
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      name:  mongoapp
      labels:
        app: mongoapp
    spec:
      containers:
      - name: mongocontainerapp
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: obinna
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: obinna@123
        volumeMounts:
        - name: mongodb-hostpath-pv
          mountPath: /data/db
      volumes:
      - name: mongodb-hostpath-pv
        persistenVolumeClaim:
          claimName: pvc-hostpath
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
spec:
  selector:
    app: mongoapp
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/kube"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi