apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongoapp
  labels:
    app: mongoapp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      name:  mongoapp
      labels:
        app: mongoapp
    spec:
      containers:
      - name: mongocontainerapp
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: obinna
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: obinna@123
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
spec:
  selector:
    app: mongoapp
  ports:
  - port: 27017
    targetPort: 27017