apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  replicas: 4
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapp
      labels:
        app: javawebapp
    spec:
      nodeSelector:
        node: dbnode #label the node using kubectl label nodes node-1 node=dbnode
      containers:
      - name: javawebapp
        image: obinnaaliogor/java-web-app
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 3000m
            memory: 856Mi
---
kind: Service  
apiVersion: v1  
metadata:
  name: webappsvc 
spec:
  type: NodePort
  ports:
  - targetPort: 8080   
    port: 80 
  selector:
    app: javawebapp
